name: dartwebserver
version: 0.0.2
description: >
  A web server
dependencies:
  unittest: any
  logging: any
  sqljocky: 
    git: git@github.com:jamesots/sqljocky.git
  options_file:
    git: git@github.com:jamesots/optionsfile.git
    