name: dartwebserver
version: 0.0.9
description: A web server
dependencies:
  logging: any
  options_file: any
  sqljocky: any
  mime: any
  path: any
dev_dependencies:
  test: ">=0.12.3 <0.13.0"
  mockito: ">=0.10.1 <0.11.0"
